<?php

namespace ReclamationBundle\Repository;

/**
 * ReclamationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReclamationRepository extends \Doctrine\ORM\EntityRepository
{
    public function updatetask($id,Request $request)
    {
        $reponse = $request->get('reponse');
        $decision = $request->get('decision');
        $query = $this->getEntityManager()->createQuery('UPDATE ReclamationBundle:Reclamation r SET r.statut = :stat , r.reponse = :rep ,r.decision = :dec WHERE t.id = :idtest');
        $query->setParameter('rep', $reponse);
        $query->setParameter('stat', "traitement effectué");
        $query->setParameter('dec', $decision);
        $query->setParameter('idtest', $id);
        $query->execute();
    }
}
