<?php
/**
 * Created by PhpStorm.
 * User: hp
 * Date: 22/11/2018
 * Time: 17:09
 */

namespace AnnuaireBundle\Service;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\File\UploadedFile;

class FileUploader
{
    private $targetDirectory;

    public function __construct($targetDirectory)
    {
        $this->targetDirectory = $targetDirectory;
    }

    /**
     * @param UploadedFile $file
     * @return string
     */
    public function upload(UploadedFile $file)
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps

        $fileName = md5(uniqid()).'.'.$file->guessExtension();

        // Move the file to the directory where files are stored
        try {
            $file->move($this->getTargetDirectory(),$fileName);
        } catch (FileException $e) {
            // ... handle exception if something happens during file upload
        }

        return $fileName;
    }

    public function getTargetDirectory()
    {
        return $this->targetDirectory;
    }

}