<?php

namespace AnnuaireBundle\Entity;

/**
 * CommentRecetteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRecetteRepository extends \Doctrine\ORM\EntityRepository
{
    
}
