<?php

namespace PatisserieBundle\Repository;

/**
 * ReservationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Doctrine\ORM\EntityRepository
{
    public function findMyReservations($id){
        $query=$this->getEntityManager()
            ->createQuery("SELECT r FROM PatisserieBundle:Reservation r WHERE r.iduser=:id")
            ->setParameter('id',$id);
        return $query->getResult();
    }

    public function mesReservations($id){
        $query=$this->getEntityManager()
            ->createQuery("SELECT r FROM PatisserieBundle:Reservation r WHERE r.idpat=:id")
            ->setParameter('id',$id);
        return $query->getResult();
    }

    public function allReservations($id){
        $query=$this->getEntityManager()
            ->createQuery("SELECT r FROM PatisserieBundle:Reservation r JOIN r.idpat p WHERE p.idprop=:id")
            ->setParameter('id',$id);
        return $query->getResult();
    }
}
