services:
#    produit.example:
#        class: ProduitBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
parameters:
  image_directory: '%kernel.project_dir%/web/ressources'