recette:
    resource: "@recetteBundle/Resources/config/routing.yml"
    prefix:   /recette

produit:
    resource: "@ProduitBundle/Resources/config/routing.yml"
    prefix:   /prod

reclamation:
    resource: "@ReclamationBundle/Resources/config/routing.yml"
    prefix:   /rec
fete:
    resource: "@FeteBundle/Resources/config/routing.yml"
    prefix:   /fete

front_office_patisserie:
    resource: "@FrontOfficePatisserieBundle/Resources/config/routing.yml"
    prefix:   /pat

front_office_event:
    resource: "@FrontOfficeEventBundle/Resources/config/routing.yml"
    prefix:   /evenmt

back_office_back:
    resource: "@BackOfficeBackBundle/Resources/config/routing.yml"
    prefix:   /back

front_office_forum:
    resource: "@FrontOfficeForumBundle/Resources/config/routing.yml"
    prefix:   /forum

evenement:
    resource: "@EvenementBundle/Resources/config/routing.yml"
    prefix:   /event

patisserie:
    resource: "@PatisserieBundle/Resources/config/routing.yml"
    prefix:   /annuaire

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

annuaire:
    resource: "@AnnuaireBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

