user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /user

annuaire:
    resource: "@AnnuaireBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"