patisserie_reservation:
    resource: "@PatisserieBundle/Resources/config/routing/reservation.yml"
    prefix:   /reservation

patisserie_homepage:
    path:     /
    defaults: { _controller: PatisserieBundle:Patisserie:afficher }

patisserie_ajout:
    path:     /ajout
    defaults: { _controller: PatisserieBundle:Patisserie:ajouter }

patisserie_modifier:
    path:     /modifier
    defaults: { _controller: PatisserieBundle:Patisserie:modifier }

patisserie_supprimer:
    path:     /supprimer
    defaults: { _controller: PatisserieBundle:Patisserie:supprimer }

patisserie_detail:
    path:     /affichage
    defaults: { _controller: PatisserieBundle:Patisserie:detail }

patisserie_detailclient:
  path:     /detail
  defaults: { _controller: PatisserieBundle:Patisserie:detailclient }

client_homepage:
  path:     /home
  defaults: { _controller: PatisserieBundle:Patisserie:afficherclient }


patisserie_liste:
  path:     /all
  defaults: { _controller: PatisserieBundle:Patisserie:liste }


reservation_index:
  path:     /reservations
  defaults: { _controller: PatisserieBundle:Reservation:afficher }
  methods:  GET

reservation_afficher:
  path:     /reservationPat
  defaults: { _controller: PatisserieBundle:Reservation:afficherPat }
  methods:  GET

reservation_new:
  path:     /Rnew
  defaults: { _controller: PatisserieBundle:Reservation:new }
  methods:  [GET, POST]

reservation_edit:
  path:     /Redit
  defaults: { _controller: PatisserieBundle:Reservation:edit }
  methods:  [GET, POST]

reservation_delete:
  path:     /Rdelete
  defaults: { _controller: PatisserieBundle:Reservation:delete }
  methods:  DELETE


