patisserie_homepage:
    path:     /
    defaults: { _controller: PatisserieBundle:Patisserie:afficher }

patisserie_ajout:
    path:     /ajout
    defaults: { _controller: PatisserieBundle:Patisserie:ajouter }

patisserie_modifier:
    path:     /modifier
    defaults: { _controller: PatisserieBundle:Patisserie:modifier }

patisserie_supprimer:
    path:     /supprimer
    defaults: { _controller: PatisserieBundle:Patisserie:supprimer }

patisserie_detail:
    path:     /affichage
    defaults: { _controller: PatisserieBundle:Patisserie:detail }

client_homepage:
  path:     /home
  defaults: { _controller: PatisserieBundle:Patisserie:afficherclient }


patisserie_liste:
  path:     /all
  defaults: { _controller: PatisserieBundle:Patisserie:liste }

