<?php

namespace EvenementBundle\Repository;

/**
 * evenementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EvenementRepository extends \Doctrine\ORM\EntityRepository
{
    public function findEvenement($nomE){
        $query=$this->getEntityManager()
            ->createQuery("SELECT p FROM EvenementBundle:Evenements p WHERE p.nomE LIKE :nomE ")
            ->setParameter('nomE','%'.$nomE.'%');
        return $query->getResult();
    }

    public function mesEvenements($id){
        $query=$this->getEntityManager()
            ->createQuery("SELECT p FROM EvenementBundle:Evenements p WHERE p.user_id= :id")
            ->setParameter('id',$id);
        return $query->getResult();
    }


}



