annuaire_homepage:
    path:     /
    defaults: { _controller: AnnuaireBundle:Default:index }

interface_principal:
    path:     /interfaceAccueil
    defaults: { _controller: AnnuaireBundle:Navigation:home }

interface_patisseries:
    path:     /interfacePat
    defaults: { _controller: AnnuaireBundle:Navigation:patisseries }

interface_evenements:
    path:     /interfaceEv
    defaults: { _controller: AnnuaireBundle:Navigation:evenement }

interface_forum:
    path:     /interfaceForum
    defaults: { _controller: AnnuaireBundle:Navigation:forum }