reclamation_crud:
    resource: "@ReclamationBundle/Resources/config/routing/reclamation.yml"
    prefix:   /crudRec

reclamation_homepage:
    path:     /reclamation
    defaults: { _controller: ReclamationBundle:Default:index }
